name: Daily Task Update Job

on:
  schedule:
    - cron: "30 18 * * 1-5"  # 12:00 AM IST Monâ€“Fri
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python taskspace/test.py
